alias ..="cd .."
alias ...="cd ../.."
alias h="cd ~"
alias c="clear"
alias ls="ls --color=auto"
alias ll="ls -la"
alias l="ls -F"
alias gs="git status"
alias ga="git add ."
alias gc="git commit -m"
alias gp="git push"
